# Generated by Django 5.0.6 on 2024-06-12 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pizza', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pizza',
            name='images',
            field=models.ImageField(blank=True, default='media/images/default_pizza_pic.jpg', help_text='upload pizza image', upload_to='media/images', verbose_name='Pizza Image'),
        ),
    ]
