# Generated by Django 5.0.6 on 2024-06-12 09:56

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pizza', '0002_pizza_images'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BasePrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('base_type', models.CharField(choices=[('THIN', 'Thin Crust'), ('THICK', 'Thick Crust'), ('CHEESE', 'Cheese Stuffed Crust')], max_length=200, unique=True)),
                ('price', models.FloatField(default=50)),
            ],
        ),
        migrations.CreateModel(
            name='CheesePrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cheese_option', models.CharField(choices=[('NO', 'No Extra Cheese'), ('YES', 'Extra Cheese')], max_length=10, unique=True)),
                ('price', models.FloatField(default=50)),
            ],
        ),
        migrations.CreateModel(
            name='SizePrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.CharField(choices=[('SM', 'Small'), ('MD', 'Medium'), ('LG', 'Large'), ('XL', 'Extra Large')], max_length=10, unique=True)),
                ('price', models.FloatField(default=100)),
            ],
        ),
        migrations.AddField(
            model_name='order',
            name='amount',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='order',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('ORDER_RECEIVED', 'Order Received'), ('PREPARING', 'Preparing'), ('READY_FOR_DELIVERY', 'Ready for Delivery'), ('ON_THE_WAY', 'On the Way'), ('DELIVERED', 'Delivered'), ('CANCELLED', 'Cancelled')], default='ORDER_RECEIVED', max_length=300),
        ),
        migrations.AddField(
            model_name='topping',
            name='price',
            field=models.FloatField(default=20),
        ),
        migrations.AlterField(
            model_name='order',
            name='customer_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='pizza',
            name='images',
            field=models.ImageField(blank=True, default='media/images/default_pizza_pic.jpg', help_text='Upload pizza image', upload_to='media/images', verbose_name='Pizza Image'),
        ),
        migrations.AlterField(
            model_name='pizza',
            name='base',
            field=models.OneToOneField(default='THIN', on_delete=django.db.models.deletion.DO_NOTHING, to='pizza.baseprice'),
        ),
        migrations.AlterField(
            model_name='pizza',
            name='extra_cheese',
            field=models.OneToOneField(default='NO', on_delete=django.db.models.deletion.DO_NOTHING, to='pizza.cheeseprice'),
        ),
        migrations.AlterField(
            model_name='pizza',
            name='size',
            field=models.OneToOneField(default='SM', on_delete=django.db.models.deletion.DO_NOTHING, to='pizza.sizeprice'),
        ),
    ]
