# Generated by Django 4.2.5 on 2024-06-16 15:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pizza', '0003_baseprice_cheeseprice_sizeprice_order_amount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pizza',
            name='base',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='pizza.baseprice'),
        ),
        migrations.AlterField(
            model_name='pizza',
            name='extra_cheese',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='pizza.cheeseprice'),
        ),
        migrations.AlterField(
            model_name='pizza',
            name='images',
            field=models.ImageField(blank=True, default='images/default_pizza_pic.jpg', help_text='Upload pizza image', upload_to='images', verbose_name='Pizza Image'),
        ),
        migrations.AlterField(
            model_name='pizza',
            name='size',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='pizza.sizeprice'),
        ),
    ]
