# Generated by Django 4.2.5 on 2024-06-28 09:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pizza', '0005_alter_pizza_images'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='quantity',
        ),
        migrations.AddField(
            model_name='order',
            name='phone_number',
            field=models.CharField(default='1234567890', max_length=15),
        ),
        migrations.RemoveField(
            model_name='order',
            name='pizza',
        ),
        migrations.CreateModel(
            name='OrderPizza',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('price', models.FloatField(default=0)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pizza.order')),
                ('pizza', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pizza.pizza')),
            ],
        ),
        migrations.AddField(
            model_name='order',
            name='pizza',
            field=models.ManyToManyField(through='pizza.OrderPizza', to='pizza.pizza'),
        ),
    ]
